// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

pub use self::imp::*;

#[allow(renamed_and_removed_lints)]
#[allow(dead_code)]
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::upper_case_acronyms)]
#[allow(clippy::zero_repeat_side_effects)]
#[warn(single_use_lifetimes)]
mod imp {
    #[allow(unused_imports, clippy::wildcard_imports)]
    use super::*;
    use libbpf_rs::libbpf_sys;
    use libbpf_rs::skel::OpenSkel;
    use libbpf_rs::skel::Skel;
    use libbpf_rs::skel::SkelBuilder;
    use libbpf_rs::AsRawLibbpf as _;
    use libbpf_rs::MapCore as _;
    fn build_skel_config(
    ) -> libbpf_rs::Result<libbpf_rs::__internal_skel::ObjectSkeletonConfig<'static>> {
        let mut builder = libbpf_rs::__internal_skel::ObjectSkeletonConfigBuilder::new(DATA);
        builder
            .name("test_bpf")
            .map("per_cpu_flows", false)
            .map("test_bpf.bss", true)
            .prog("test");
        builder.build()
    }
    pub struct OpenTestMaps<'obj> {
        pub per_cpu_flows: libbpf_rs::OpenMapMut<'obj>,
        pub bss: libbpf_rs::OpenMapMut<'obj>,
        pub bss_data: Option<&'obj mut types::bss>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenTestMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::OpenObject,
        ) -> libbpf_rs::Result<Self> {
            let mut per_cpu_flows = None;
            let mut bss = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "per_cpu_flows" => per_cpu_flows = Some(map),
                    "test_bpf.bss" => bss = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                per_cpu_flows: per_cpu_flows.expect("map `per_cpu_flows` not present"),
                bss: bss.expect("map `bss` not present"),
                bss_data: unsafe {
                    config
                        .map_mmap_ptr(1)
                        .expect("BPF map `bss` does not have mmap pointer")
                        .cast::<types::bss>()
                        .as_mut()
                },
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct TestMaps<'obj> {
        pub per_cpu_flows: libbpf_rs::MapMut<'obj>,
        pub bss: libbpf_rs::MapMut<'obj>,
        pub bss_data: Option<&'obj mut types::bss>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> TestMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::Object,
        ) -> libbpf_rs::Result<Self> {
            let mut per_cpu_flows = None;
            let mut bss = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::Object, &'obj mut libbpf_rs::Object>(object)
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "per_cpu_flows" => per_cpu_flows = Some(map),
                    "test_bpf.bss" => bss = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                per_cpu_flows: per_cpu_flows.expect("map `per_cpu_flows` not present"),
                bss: bss.expect("map `bss` not present"),
                bss_data: unsafe {
                    config
                        .map_mmap_ptr(1)
                        .expect("BPF map `bss` does not have mmap pointer")
                        .cast::<types::bss>()
                        .as_mut()
                },
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct OpenTestProgs<'obj> {
        pub test: libbpf_rs::OpenProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenTestProgs<'obj> {
        unsafe fn new(object: &mut libbpf_rs::OpenObject) -> libbpf_rs::Result<Self> {
            let mut test = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            for prog in object.progs_mut() {
                let name = prog.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "prog has invalid name",
                    ))
                })?;
                match name {
                    "test" => test = Some(prog),
                    _ => panic!("encountered unexpected prog: `{name}`"),
                }
            }

            let slf = Self {
                test: test.expect("prog `test` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct TestProgs<'obj> {
        pub test: libbpf_rs::ProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> TestProgs<'obj> {
        #[allow(unused_variables)]
        fn new(open_progs: OpenTestProgs<'obj>) -> Self {
            Self {
                test: unsafe {
                    libbpf_rs::ProgramMut::new_mut(open_progs.test.as_libbpf_object().as_mut())
                },
                _phantom: std::marker::PhantomData,
            }
        }
    }
    struct OwnedRef<'obj, O> {
        object: Option<&'obj mut std::mem::MaybeUninit<O>>,
    }

    impl<'obj, O> OwnedRef<'obj, O> {
        /// # Safety
        /// The object has to be initialized.
        unsafe fn new(object: &'obj mut std::mem::MaybeUninit<O>) -> Self {
            Self {
                object: Some(object),
            }
        }

        fn as_ref(&self) -> &O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_ref().unwrap().assume_init_ref() }
        }

        fn as_mut(&mut self) -> &mut O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_mut().unwrap().assume_init_mut() }
        }

        fn take(mut self) -> &'obj mut std::mem::MaybeUninit<O> {
            self.object.take().unwrap()
        }
    }

    impl<O> Drop for OwnedRef<'_, O> {
        fn drop(&mut self) {
            if let Some(object) = &mut self.object {
                unsafe { object.assume_init_drop() }
            }
        }
    }

    #[derive(Default)]
    pub struct TestSkelBuilder {
        pub obj_builder: libbpf_rs::ObjectBuilder,
    }

    impl<'obj> TestSkelBuilder {
        fn open_opts_impl(
            self,
            open_opts: *const libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenTestSkel<'obj>> {
            let skel_config = build_skel_config()?;
            let skel_ptr = skel_config.as_libbpf_object();

            let ret =
                unsafe { libbpf_sys::bpf_object__open_skeleton(skel_ptr.as_ptr(), open_opts) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            // SAFETY: `skel_ptr` points to a valid object after the
            //         open call.
            let obj_ptr = unsafe { *skel_ptr.as_ref().obj };
            // SANITY: `bpf_object__open_skeleton` should have
            //         allocated the object.
            let obj_ptr = std::ptr::NonNull::new(obj_ptr).unwrap();
            // SAFETY: `obj_ptr` points to an opened object after
            //         skeleton open.
            let obj = unsafe { libbpf_rs::OpenObject::from_ptr(obj_ptr) };
            let _obj = object.write(obj);
            // SAFETY: We just wrote initialized data to `object`.
            let mut obj_ref = unsafe { OwnedRef::new(object) };

            #[allow(unused_mut)]
            let mut skel = OpenTestSkel {
                maps: unsafe { OpenTestMaps::new(&skel_config, obj_ref.as_mut())? },
                progs: unsafe { OpenTestProgs::new(obj_ref.as_mut())? },
                obj: obj_ref,
                // SAFETY: Our `struct_ops` type contains only pointers,
                //         which are allowed to be NULL.
                // TODO: Generate and use a `Default` representation
                //       instead, to cut down on unsafe code.
                struct_ops: unsafe { std::mem::zeroed() },
                skel_config,
            };

            Ok(skel)
        }
    }

    impl<'obj> SkelBuilder<'obj> for TestSkelBuilder {
        type Output = OpenTestSkel<'obj>;
        fn open(
            self,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenTestSkel<'obj>> {
            self.open_opts_impl(std::ptr::null(), object)
        }

        fn open_opts(
            self,
            open_opts: libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenTestSkel<'obj>> {
            self.open_opts_impl(&open_opts, object)
        }

        fn object_builder(&self) -> &libbpf_rs::ObjectBuilder {
            &self.obj_builder
        }
        fn object_builder_mut(&mut self) -> &mut libbpf_rs::ObjectBuilder {
            &mut self.obj_builder
        }
    }

    #[derive(Debug, Clone)]
    #[repr(C)]
    pub struct StructOps {}

    impl StructOps {}
    pub mod types {
        #[allow(unused_imports)]
        use super::*;
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct flows_t {
            pub r#type: *mut [i32; 9],
            pub max_entries: *mut [i32; 1024],
            pub key: *mut flow_key_t,
            pub value: *mut flow_entry_t,
        }
        impl Default for flows_t {
            fn default() -> Self {
                Self {
                    r#type: std::ptr::null_mut(),
                    max_entries: std::ptr::null_mut(),
                    key: std::ptr::null_mut(),
                    value: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct flow_key_t {
            pub src_ip_be: u32,
            pub src_port_be: u16,
            pub dst_port_be: u16,
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct flow_entry_t {
            pub timestamp_ns: u64,
            pub dst_ip_be: u32,
            pub dst_port_be: u16,
            pub src_port_be: u16,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_1 {
            pub r#type: *mut [i32; 12],
            pub max_entries: *mut [i32; 33],
            pub key: *mut u32,
            pub values: [*mut flows_t; 0],
        }
        impl Default for __anon_1 {
            fn default() -> Self {
                Self {
                    r#type: std::ptr::null_mut(),
                    max_entries: std::ptr::null_mut(),
                    key: std::ptr::null_mut(),
                    values: [std::ptr::null_mut(); 0],
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct xdp_md {
            pub data: u32,
            pub data_end: u32,
            pub data_meta: u32,
            pub ingress_ifindex: u32,
            pub rx_queue_index: u32,
            pub egress_ifindex: u32,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct license {
            pub LICENSE: [i8; 4],
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct bss {
            pub key: flow_key_t,
            pub entry: flow_entry_t,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct maps {
            pub per_cpu_flows: __anon_1,
        }
    }
    pub struct OpenTestSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::OpenObject>,
        pub maps: OpenTestMaps<'obj>,
        pub progs: OpenTestProgs<'obj>,
        pub struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
    }

    impl<'obj> OpenSkel<'obj> for OpenTestSkel<'obj> {
        type Output = TestSkel<'obj>;
        fn load(self) -> libbpf_rs::Result<TestSkel<'obj>> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();

            let ret = unsafe { libbpf_sys::bpf_object__load_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj_ref = self.obj.take();
            let open_obj = std::mem::replace(obj_ref, std::mem::MaybeUninit::uninit());
            // SAFETY: `open_obj` is guaranteed to be properly
            //         initialized as it came from an `OwnedRef`.
            let obj_ptr = unsafe { open_obj.assume_init().take_ptr() };
            // SAFETY: `obj_ptr` points to a loaded object after
            //         skeleton load.
            let obj = unsafe { libbpf_rs::Object::from_ptr(obj_ptr) };
            // SAFETY: `OpenObject` and `Object` are guaranteed to
            //         have the same memory layout.
            let obj_ref = unsafe {
                std::mem::transmute::<
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::Object>,
                >(obj_ref)
            };
            let _obj = obj_ref.write(obj);
            // SAFETY: We just wrote initialized data to `obj_ref`.
            let mut obj_ref = unsafe { OwnedRef::new(obj_ref) };

            Ok(TestSkel {
                maps: unsafe { TestMaps::new(&self.skel_config, obj_ref.as_mut())? },
                progs: TestProgs::new(self.progs),
                obj: obj_ref,
                struct_ops: self.struct_ops,
                skel_config: self.skel_config,
                links: TestLinks::default(),
            })
        }

        fn open_object(&self) -> &libbpf_rs::OpenObject {
            self.obj.as_ref()
        }

        fn open_object_mut(&mut self) -> &mut libbpf_rs::OpenObject {
            self.obj.as_mut()
        }
    }
    #[derive(Default)]
    pub struct TestLinks {
        pub test: Option<libbpf_rs::Link>,
    }
    pub struct TestSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::Object>,
        pub maps: TestMaps<'obj>,
        pub progs: TestProgs<'obj>,
        struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
        pub links: TestLinks,
    }

    unsafe impl Send for TestSkel<'_> {}
    unsafe impl Sync for TestSkel<'_> {}

    impl<'obj> Skel<'obj> for TestSkel<'obj> {
        fn object(&self) -> &libbpf_rs::Object {
            self.obj.as_ref()
        }

        fn object_mut(&mut self) -> &mut libbpf_rs::Object {
            self.obj.as_mut()
        }
        fn attach(&mut self) -> libbpf_rs::Result<()> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();
            let ret = unsafe { libbpf_sys::bpf_object__attach_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            self.links = TestLinks {
                test: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(0)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
            };

            Ok(())
        }
    }
    impl TestSkel<'_> {
        pub fn struct_ops_raw(&self) -> *const StructOps {
            &self.struct_ops
        }

        pub fn struct_ops(&self) -> &StructOps {
            &self.struct_ops
        }
    }
    const DATA: &[u8] = &[
        127, 69, 76, 70, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 247, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0,
        64, 0, 9, 0, 1, 0, 0, 46, 115, 116, 114, 116, 97, 98, 0, 46, 115, 121, 109, 116, 97, 98, 0,
        120, 100, 112, 0, 108, 105, 99, 101, 110, 115, 101, 0, 46, 98, 115, 115, 0, 46, 109, 97,
        112, 115, 0, 116, 101, 115, 116, 46, 98, 112, 102, 46, 99, 0, 116, 101, 115, 116, 0, 76,
        73, 67, 69, 78, 83, 69, 0, 107, 101, 121, 0, 101, 110, 116, 114, 121, 0, 112, 101, 114, 95,
        99, 112, 117, 95, 102, 108, 111, 119, 115, 0, 46, 66, 84, 70, 0, 46, 66, 84, 70, 46, 101,
        120, 116, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        40, 0, 0, 0, 4, 0, 241, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3,
        0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 51, 0, 0, 0, 18, 0, 3, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 56, 0, 0, 0, 17, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        4, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 17, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0,
        0, 0, 68, 0, 0, 0, 17, 0, 5, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 74, 0, 0,
        0, 17, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 183, 0, 0, 0, 2, 0, 0, 0,
        149, 0, 0, 0, 0, 0, 0, 0, 71, 80, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 159, 235, 1, 0, 24, 0, 0, 0, 0, 0, 0, 0, 108, 3, 0, 0,
        108, 3, 0, 0, 166, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 4,
        0, 0, 0, 32, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 12, 0, 0,
        0, 5, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 6, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 33, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        2, 8, 0, 0, 0, 25, 0, 0, 0, 0, 0, 0, 8, 9, 0, 0, 0, 31, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0,
        32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 11, 0, 0, 0, 44, 0, 0, 0, 4, 0, 0, 4, 32, 0, 0, 0, 52,
        0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 57, 0, 0, 0, 14, 0, 0, 0, 64, 0, 0, 0, 69, 0, 0, 0, 16,
        0, 0, 0, 128, 0, 0, 0, 73, 0, 0, 0, 17, 0, 0, 0, 192, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 13,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 2, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 0,
        4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 28, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 32, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 3, 0, 0, 0, 0, 10, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 4, 24,
        0, 0, 0, 52, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 57, 0, 0, 0, 5, 0, 0, 0, 64, 0, 0, 0, 69, 0,
        0, 0, 7, 0, 0, 0, 128, 0, 0, 0, 79, 0, 0, 0, 18, 0, 0, 0, 192, 0, 0, 0, 86, 0, 0, 0, 0, 0,
        0, 14, 19, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 22, 0, 0, 0, 100, 0, 0, 0, 6, 0, 0,
        4, 24, 0, 0, 0, 107, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 112, 0, 0, 0, 8, 0, 0, 0, 32, 0, 0,
        0, 121, 0, 0, 0, 8, 0, 0, 0, 64, 0, 0, 0, 131, 0, 0, 0, 8, 0, 0, 0, 96, 0, 0, 0, 147, 0, 0,
        0, 8, 0, 0, 0, 128, 0, 0, 0, 162, 0, 0, 0, 8, 0, 0, 0, 160, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        13, 2, 0, 0, 0, 177, 0, 0, 0, 21, 0, 0, 0, 181, 0, 0, 0, 1, 0, 0, 12, 23, 0, 0, 0, 186, 0,
        0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 25, 0, 0, 0,
        4, 0, 0, 0, 4, 0, 0, 0, 191, 0, 0, 0, 0, 0, 0, 14, 26, 0, 0, 0, 1, 0, 0, 0, 199, 0, 0, 0,
        3, 0, 0, 4, 8, 0, 0, 0, 210, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 220, 0, 0, 0, 29, 0, 0, 0,
        32, 0, 0, 0, 232, 0, 0, 0, 29, 0, 0, 0, 48, 0, 0, 0, 244, 0, 0, 0, 0, 0, 0, 8, 30, 0, 0, 0,
        250, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 16, 0, 0, 0, 69, 0, 0, 0, 0, 0, 0, 14, 28, 0, 0, 0,
        1, 0, 0, 0, 9, 1, 0, 0, 4, 0, 0, 4, 16, 0, 0, 0, 22, 1, 0, 0, 33, 0, 0, 0, 0, 0, 0, 0, 35,
        1, 0, 0, 8, 0, 0, 0, 64, 0, 0, 0, 232, 0, 0, 0, 29, 0, 0, 0, 96, 0, 0, 0, 220, 0, 0, 0, 29,
        0, 0, 0, 112, 0, 0, 0, 45, 1, 0, 0, 0, 0, 0, 8, 34, 0, 0, 0, 51, 1, 0, 0, 0, 0, 0, 1, 8, 0,
        0, 0, 64, 0, 0, 0, 70, 1, 0, 0, 0, 0, 0, 14, 32, 0, 0, 0, 1, 0, 0, 0, 143, 1, 0, 0, 1, 0,
        0, 15, 4, 0, 0, 0, 27, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 151, 1, 0, 0, 2, 0, 0, 15, 24, 0,
        0, 0, 31, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 35, 0, 0, 0, 8, 0, 0, 0, 16, 0, 0, 0, 156, 1, 0,
        0, 1, 0, 0, 15, 24, 0, 0, 0, 20, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 105, 110, 116, 0, 95,
        95, 65, 82, 82, 65, 89, 95, 83, 73, 90, 69, 95, 84, 89, 80, 69, 95, 95, 0, 95, 95, 117, 51,
        50, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32, 105, 110, 116, 0, 102, 108, 111, 119,
        115, 95, 116, 0, 116, 121, 112, 101, 0, 109, 97, 120, 95, 101, 110, 116, 114, 105, 101,
        115, 0, 107, 101, 121, 0, 118, 97, 108, 117, 101, 0, 118, 97, 108, 117, 101, 115, 0, 112,
        101, 114, 95, 99, 112, 117, 95, 102, 108, 111, 119, 115, 0, 120, 100, 112, 95, 109, 100, 0,
        100, 97, 116, 97, 0, 100, 97, 116, 97, 95, 101, 110, 100, 0, 100, 97, 116, 97, 95, 109,
        101, 116, 97, 0, 105, 110, 103, 114, 101, 115, 115, 95, 105, 102, 105, 110, 100, 101, 120,
        0, 114, 120, 95, 113, 117, 101, 117, 101, 95, 105, 110, 100, 101, 120, 0, 101, 103, 114,
        101, 115, 115, 95, 105, 102, 105, 110, 100, 101, 120, 0, 99, 116, 120, 0, 116, 101, 115,
        116, 0, 99, 104, 97, 114, 0, 76, 73, 67, 69, 78, 83, 69, 0, 102, 108, 111, 119, 95, 107,
        101, 121, 95, 116, 0, 115, 114, 99, 95, 105, 112, 95, 98, 101, 0, 115, 114, 99, 95, 112,
        111, 114, 116, 95, 98, 101, 0, 100, 115, 116, 95, 112, 111, 114, 116, 95, 98, 101, 0, 95,
        95, 117, 49, 54, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32, 115, 104, 111, 114, 116, 0,
        102, 108, 111, 119, 95, 101, 110, 116, 114, 121, 95, 116, 0, 116, 105, 109, 101, 115, 116,
        97, 109, 112, 95, 110, 115, 0, 100, 115, 116, 95, 105, 112, 95, 98, 101, 0, 95, 95, 117,
        54, 52, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32, 108, 111, 110, 103, 32, 108, 111,
        110, 103, 0, 101, 110, 116, 114, 121, 0, 47, 104, 111, 109, 101, 47, 101, 102, 97, 103,
        101, 114, 104, 111, 47, 108, 105, 98, 98, 112, 102, 45, 116, 101, 115, 116, 47, 115, 114,
        99, 47, 98, 112, 102, 47, 116, 101, 115, 116, 46, 98, 112, 102, 46, 99, 0, 32, 32, 32, 32,
        114, 101, 116, 117, 114, 110, 32, 88, 68, 80, 95, 80, 65, 83, 83, 59, 0, 108, 105, 99, 101,
        110, 115, 101, 0, 46, 98, 115, 115, 0, 46, 109, 97, 112, 115, 0, 120, 100, 112, 0, 0, 0, 0,
        0, 0, 0, 159, 235, 1, 0, 32, 0, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 20, 0, 0, 0, 28, 0, 0, 0,
        48, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 162, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 16,
        0, 0, 0, 162, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 76, 1, 0, 0, 122, 1, 0, 0, 5, 164, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0,
        0, 0, 0, 0, 0, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 168, 0, 0, 0, 0, 0, 0, 0, 192, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0,
        0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 17, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 104, 1, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 21, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 120, 1, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 29, 0, 0, 0, 8, 0, 0, 0, 3,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 1, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 34, 0, 0, 0,
        1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 1, 0, 0, 0, 0, 0, 0, 24,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 88, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 152, 1, 0, 0,
        0, 0, 0, 0, 42, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 93, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        200, 6, 0, 0, 0, 0, 0, 0, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ];
}
